FIND_PACKAGE(Ruby REQUIRED)

if (RUST_INCLUDE_PATH AND RUST_SOURCE_DIR)
   set(RUST_FIND_QUIETLY TRUE)
endif (RUST_INCLUDE_PATH AND RUST_SOURCE_DIR)

FIND_PATH(RUST_INCLUDE_DIR rust_conversions.hh
   $ENV{RUSTDIR}/include
   /usr/include/rust
   /usr/local/include/rust
   )

SET(RUST_INCLUDE_PATH ${RUST_INCLUDE_DIR} ${RUBY_INCLUDE_PATH})

FIND_PATH(RUST_SOURCE_DIR rust.rb
   $ENV{RUSTDIR}
   ${RUBY_SITEDIR}
   )
